apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: edu-goofy-allen
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      project: nginx
  template:
    metadata:
      labels:
        project: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.3
          ports:
          - containerPort: 80
          - containerPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: edu-goofy-allen
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      project: django
  template:
    metadata:
      labels:
        project: django
    spec:
      containers:
        - name: django-container
          image: sdieul/task1_backend_main_django:latest
#          lifecycle:
#            postStart:
#              exec:
#                command: ['chmod', '0600', '/root/.postgresql/root.crt']

          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret-config
            - secretRef:
                name: postgres
          env:
            - name: DATABASE_URL
              value: postgresql://$(username):$(password)@$(host):$(port)/$(name)?sslmode=verify-full&target_session_attrs=any&sslrootcert=/root/.postgresql/root.crt

          ports:
            - containerPort: 80
          volumeMounts:
            - name: psql-certs
              mountPath: '/root/.postgresql/'
              readOnly: False
      volumes:
        - name: psql-certs
          secret:
            secretName: psql-cert
            defaultMode: 384


---
apiVersion: v1
kind: Pod
metadata:
  name: temp-ubuntu-pod
  namespace: edu-goofy-allen
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest

      command: ["/bin/sh","-c"]
      args: [
        'apt-get update;
         apt install wget -y &&
         apt install postgresql-client -y &&
         mkdir -p ~/.postgresql &&
         wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document ~/.postgresql/root.crt &&
         chmod 0600 ~/.postgresql/root.crt &&
         tail -f /dev/null'
      ]

      envFrom:
        - secretRef:
            name: postgres
