apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: edu-goofy-allen
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      project: nginx
  template:
    metadata:
      labels:
        project: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.3
          ports:
          - containerPort: 80
          - containerPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: edu-goofy-allen
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      project: django
  template:
    metadata:
      labels:
        project: django
    spec:
      containers:
        - name: django-container
          image: sdieul/task1_backend_main_django:latest
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret-config
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: temp-ubuntu-pod
  namespace: edu-goofy-allen
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest

      command: ["/bin/sh","-c"]
      args: [
        'apt-get update;
         apt install wget -y &&
         apt install postgresql-client -y &&
         mkdir -p ~/.postgresql &&
         wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document ~/.postgresql/root.crt &&
         chmod 0600 ~/.postgresql/root.crt &&
         tail -f /dev/null'
      ]

      envFrom:
        - secretRef:
            name: postgres
