apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-django-sessions
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 20
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: django-container
              image: sdieul/task1_backend_main_django:latest
              envFrom:
                - configMapRef:
                    name: django-config
              command: ["python", "manage.py", "clearsessions"]
          restartPolicy: Never
