apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    env: dev
    app: main
spec:
  replicas: 1
  selector:
    matchLabels:
      project: webapp
  template:
    metadata:
      labels:
        project: webapp
    spec:
      containers:
        - name: django-container
          image: sdieul/task1_backend_main_django:latest
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret-config
          ports:
            - containerPort: 80